app/mod_auction/controllers.py
from flask import Blueprint, session, redirect, url_for, request, render_template, flash
from sqlalchemy import func
from app import db
from app.mod_auction.forms import BidForm
from app.mod_member.forms import UploadBookForm
from app.models import Book, Bid, User, Auction

mod_auction = Blueprint('auction', __name__, url_prefix='/auction')


# Sign up - Registration for new users
@mod_auction.route('/book/<bookID>', methods=['GET', 'POST'])
def book(bookID):
    form = BidForm()
    bookS = db.session.query(Book).filter(Book.book_id == bookID).scalar()
    print(str(db.session.query(Book).filter(Book.book_id == bookID).as_scalar()))
    aucID = db.session.query(Auction.auc_id).filter(Auction.book_id == bookID).scalar()
    print(str(db.session.query(Auction.auc_id).filter(Auction.book_id == bookID).as_scalar()))
    curPrice = db.session.query(func.max(Bid.bid_price)).filter(Bid.auc_id == aucID).scalar()
    print(str(db.session.query(func.max(Bid.bid_price)).filter(Bid.auc_id == aucID).as_scalar()))
    if request.method == 'POST':
        if not form.validate():
            flash('Bid Unsuccessful')
            return render_template('auction/book.html', form=form, book=bookS, curPrice=curPrice)
        else:
            if 'email' not in session:
                return redirect(url_for('auth.signin'))
            else:
                usrID = db.session.query(User.user_id).filter(User.email == session['email']).scalar()
                highBid = db.session.query(Bid.bid_price).filter(Bid.auc_id == aucID).\
                    filter(Bid.bid_price >= form.bid_price.data).first()
                if highBid:
                    flash('Your bid needs to be higher then the current price')
                    return render_template('auction/book.html', form=form, book=bookS, curPrice=curPrice)
                else:
                    newBid = Bid(auc_id=aucID, user_id=usrID, bid_price=form.bid_price.data)
                    db.session.add(newBid)
                    db.session.commit()
                    flash('Bid Successful')
                return render_template('auction/book.html', form=form, book=bookS, curPrice=form.bid_price.data)
    
    elif request.method == 'GET':
        return render_template('auction/book.html', form=form, book=bookS, curPrice=curPrice)

app/mod_member/controllers.py
from datetime import datetime
import json
from flask import Blueprint, session, url_for, redirect, render_template, request, g
from sqlalchemy import null
from app import db, api
from app.mod_member.forms import UploadBookForm
from app.models import User, Book, Auction


mod_member = Blueprint('member', __name__, url_prefix='/member')

@mod_member.before_request
def before_request():
    g.user = User.user_id

# Profile -
@mod_member.route('/profile/')
def profile():
    if 'email' not in session:
        return redirect(url_for('auth.signin'))

        # << sql >>
        # SELECT * FROM users WHERE email = session['email'];
    user = User.query.filter_by(email=session['email']).first()
    print user

    if user is None:
        return redirect(url_for('auth.signin'))
    else:
        books = db.session.query(Book). \
            filter(User.email == session['email']). \
            filter(Book.user_id == User.user_id)
        g.user_id = User.user_id
        return render_template('member/profile.html', books=books)


@mod_member.route('/newbook/', methods=['GET', 'POST'])
def newbook():
    form = UploadBookForm()

    if 'email' not in session:
        return redirect(url_for('auth.signin'))

    if request.method == 'POST':
        uid = db.session.query(User.user_id).filter(User.email == session['email']).scalar()

        isbnImg = "isbn" + str(form.isbn.data)
        image = api.list(isbnImg)

        sThumbnail = image['items'][0]['volumeInfo']['imageLinks']['smallThumbnail']
        lThumbnail = image['items'][0]['volumeInfo']['imageLinks']['thumbnail']

        book = Book(isbn=form.isbn.data, title=form.title.data, volume=form.volume.data,
                    author=form.author.data, publisher=form.publisher.data, year=form.year.data,
                    subject=form.subject.data, user_id=uid, smallThumbnail=sThumbnail,
                    largeThumbnail=lThumbnail)
        db.session.add(book)
        db.session.commit()

        auction = Auction(book_id=book.book_id, start_time=datetime.now(), end_time=form.endDate.data)
        db.session.add(auction)
        db.session.commit()

        return redirect(url_for('member.profile'))

    elif request.method == 'GET':
        return render_template('member/newbook.html', form=form)


@mod_member.route('/connect/')
def connect():
    return render_template('member/connect.html')


@mod_member.route('/bestBooks/')
def bestBooks():
    pass
    # best = db.session.query(Book).filter(Book.auc_id = Auction.auc_id).filter(Auction.bid)


def setGuser():
    User.user_id = g.user

app/templates/member/connect.html
{% extends "base.html" %}
        {% block content %}
            <iframe src="https://ssbp.mycampus.ca/apex/f?p=104:101:8010050558643" width="935" height="600">
              <p>Your browser does not support iframes.</p>
            </iframe>
        {% endblock %}

app/templates/member/edit.html
<!-- extends base layout -->
{% extends "base.html" %}

{% block content %}
    <h1>Edit Profile</h1>
    <form action="" method="post" name="edit">
        {{form.hidden_tag()}}
        <table>
            <tr>
                <td>Nickname:</td>
                <td>
                    {{ form.nickname(size=24) }}
                    {% for error in form.errors.nickname %}
                    <br><span style="color: red;">[{{ error }}]</span>
                    {% endfor %}
                </td>
            </tr>
            <tr>
                <td>About yourself:</td>
                <td>{{ form.about_me(cols=32, row=4) }}</td>
            </tr>
            <tr>
                <td></td>
                <td><input type="submit" value="Save Changes"></td>
            </tr>
        </table>
    </form>
{% endblock %}

app/templates/member/newbook.html
{% extends "base.html" %}
{% block content %}
    <h2>Add Book</h2>

    {% for message in form.isbn.errors %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    {% for message in form.title.errors %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    {% for message in form.author.errors %}
        <div class="flash">{{ message }}</div>
    {% endfor %}

    <form action="{{ url_for('member.newbook') }}" method="post">
        {{ form.hidden_tag() }}

        {{ form.isbn.label }}
        {{ form.isbn }}

        {{ form.title.label }}
        {{ form.title }}

        {{ form.volume.label }}
        {{ form.volume }}

        {{ form.author.label }}
        {{ form.author }}

        {{ form.publisher.label }}
        {{ form.publisher }}

        {{ form.year.label }}
        {{ form.year }}

        {{ form.subject.label }}
        {{ form.subject }}

        {{ form.endDate.label }}
        {{ form.endDate }}

        {{ form.submit }}
    </form>
{% endblock %}

app/templates/member/post.html
<div style="width:1350px;padding:5px;boarder:5px solid black;">
    <table>
        <td valign="top">
            <tr>
                {% if not book.smallThumbnail %}
                    <td><img src="http://simpleicon.com/wp-content/uploads/book-5.png" style="width:55px;height:80px"></td>
                {% else %}
                    <td><img src="{{ book.smallThumbnail }}"></td>
                {% endif %}
                <td>
                    <h2>Highest Bid</h2>
                </td>
                <td>
                    <h3>$ {{ book.curPrice }}</h3>
                </td>
                <td><h4> Title:</h4></td>
                <td>{{ book.title  }}</td></tr>
                <br>
            <tr>
                <td><h4>Author:</h4></td>
                <td>{{ book.author }}</td>
                <td><h4>  ISBN:</h4></td>
                <td>{{ book.isbn }}</td></td>
            </tr>
        </td>
    </table>
</div>

app/templates/member/profile.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbo">
        <h2>Profile</h2>
        <h3>This is {{ session['email'] }}'s profile page</h3>
    <hr>
    {% for book in books %}
        <a class="img-thumbnail" href="{{ url_for('auction.book', bookID=book.book_id) }}">
            {% include 'member/post.html' %}
        </a>
    {% endfor %}
    </div>
{% endblock %}