app/mod_auth/controllers.py
from flask import Blueprint, session, redirect, url_for, render_template, request, g
from app import db
from app.models import User
from app.mod_auth.forms import SigninForm, SignupForm

mod_auth = Blueprint('auth', __name__, url_prefix='/auth')


# Sign up - Registration for new users
@mod_auth.route('/signup/', methods=['GET', 'POST'])
def signup():
    form = SignupForm()

    if 'email' in session:
        return redirect(url_for('member.profile'))

    if request.method == 'POST':
        if not form.validate():
            return render_template('auth/signup.html', form=form)
        else:
            # << sql >>
            # INSERT INTO users (firstname, lastname, email, pwdhash)
            # VALUES (form.firstname.data, form.lastname.data, form.email.data, form.password.data)
            newuser = User(form.fname.data, form.lname.data, form.email.data, form.password.data)
            db.session.add(newuser)
            db.session.commit()
            session['email'] = newuser.email
            return redirect(url_for('member.profile'))

    elif request.method == 'GET':
        return render_template('auth/signup.html', form=form)


# Sign in - Existing member sign in
@mod_auth.route('/signin/', methods=['GET', 'POST'])
def signin():
    form = SigninForm()

    if 'email' in session:
        return redirect(url_for('member.profile'))

    if request.method == 'POST':
        if not form.validate():
            return render_template('auth/signin.html', form=form)
        else:
            session['email'] = form.email.data
            return redirect(url_for('member.profile'))
    elif request.method == 'GET':
        return render_template('auth/signin.html', form=form)


# Log out - Exit's the user session
@mod_auth.route('/logout')
def logout():
    if 'email' not in session:
        return redirect(url_for('auth.signin'))

    session.pop('email', None)
    return redirect(url_for('public.home'))

app/mod_member/controllers.py
from datetime import datetime
import json
from flask import Blueprint, session, url_for, redirect, render_template, request, g
from sqlalchemy import null
from app import db, api
from app.mod_member.forms import UploadBookForm
from app.models import User, Book, Auction


mod_member = Blueprint('member', __name__, url_prefix='/member')

@mod_member.before_request
def before_request():
    g.user = User.user_id

# Profile -
@mod_member.route('/profile/')
def profile():
    if 'email' not in session:
        return redirect(url_for('auth.signin'))

        # << sql >>
        # SELECT * FROM users WHERE email = session['email'];
    user = User.query.filter_by(email=session['email']).first()
    print user

    if user is None:
        return redirect(url_for('auth.signin'))
    else:
        books = db.session.query(Book). \
            filter(User.email == session['email']). \
            filter(Book.user_id == User.user_id)
        g.user_id = User.user_id
        return render_template('member/profile.html', books=books)


@mod_member.route('/newbook/', methods=['GET', 'POST'])
def newbook():
    form = UploadBookForm()

    if 'email' not in session:
        return redirect(url_for('auth.signin'))

    if request.method == 'POST':
        uid = db.session.query(User.user_id).filter(User.email == session['email']).scalar()

        isbnImg = "isbn" + str(form.isbn.data)
        image = api.list(isbnImg)

        sThumbnail = image['items'][0]['volumeInfo']['imageLinks']['smallThumbnail']
        lThumbnail = image['items'][0]['volumeInfo']['imageLinks']['thumbnail']

        book = Book(isbn=form.isbn.data, title=form.title.data, volume=form.volume.data,
                    author=form.author.data, publisher=form.publisher.data, year=form.year.data,
                    subject=form.subject.data, user_id=uid, smallThumbnail=sThumbnail,
                    largeThumbnail=lThumbnail)
        db.session.add(book)
        db.session.commit()

        auction = Auction(book_id=book.book_id, start_time=datetime.now(), end_time=form.endDate.data)
        db.session.add(auction)
        db.session.commit()

        return redirect(url_for('member.profile'))

    elif request.method == 'GET':
        return render_template('member/newbook.html', form=form)


@mod_member.route('/connect/')
def connect():
    return render_template('member/connect.html')


@mod_member.route('/bestBooks/')
def bestBooks():
    pass
    # best = db.session.query(Book).filter(Book.auc_id = Auction.auc_id).filter(Auction.bid)


def setGuser():
    User.user_id = g.user

app/mod_public/controllers.py
from flask import render_template, request, Blueprint, session, url_for
from sqlalchemy import func
from app import mod_public, db, api
from app.mod_public.forms import ContactForm, SearchForm
from app.models import Book, Bid, Auction


mod_public = Blueprint('public', __name__, url_prefix='/')

# Home - Home page
@mod_public.route('/')
@mod_public.route('home/', methods=['GET', 'POST'])
def home():
    form = SearchForm()

    books = db.session.query(Book).all()

    if request.method == 'POST':

        return render_template('public/home.html', form=form, books=books)

    else:

        return render_template('public/home.html', form=form, books=books)


# About - Provides basic information about bookworm
@mod_public.route('about/')
def about():
    return render_template('public/about.html')


# Contact - Allows user to contact web admin
@mod_public.route('contact/', methods=['GET', 'POST'])
def contact():
    form = ContactForm()

    if request.method == 'POST':
        if not form.validate():
            return render_template('public/contact.html', form=form)
        else:
            # << Mail method not implemented >>
            return 'Form posted.'
    elif request.method == 'GET':
        return render_template('public/contact.html', form=form)


@mod_public.route('search/', methods=['Get', 'Post'])
def search():
    form = SearchForm()
    if request.method == 'POST':
        books = Book.query.filter(Book.title == form.title.data)


        return render_template('public/search.html', books=books, form=form)
    else:
        return render_template('public/search.html', form=form)

app/templates/about.html
{% extends "base.html" %}

{% block content %}
    <h2>About</h2>
    <p>Bookworm made by students for students </p>
    <p>A beastMode Production</p>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Bookworm</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <title>Bookworm</title>

        <!-- Bootstrap core CSS -->
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- Bootstrap theme -->
        <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="theme.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="{{ url_for('static', filename='js/ie8-responsive-file-warning.js') }}"></script><![endif]-->
        <script src="{{ url_for('static', filename='js/ie-emulation-modes-warning.js') }}"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
        <![endif]-->
        <strong><link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"></strong>
    </head>
    <body>

        <header>
            <div class="container">
                <div id="navbar" class="navbar-collapse collapse">
                    <a href="{{ url_for('public.home') }}"><h1 class="logo">Bookworm</h1></a>
                <strong><nav>
                    <ul class="menu">
                        <li><a href="{{ url_for('public.home') }}">Home</a></li>
                        <li><a href="{{ url_for('public.search') }}">Search</a></li>

                        {% if 'email' in session %}
                        <li><a href="{{ url_for('member.newbook') }}">Add Book</a></li>
                        <li><a href="{{ url_for('member.profile') }}">Profile</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                        {% else %}
                        <li><a href="{{ url_for('auth.signin') }}">Sign In</a></li>
                        {% endif %}
                    </ul>
                </nav></strong>
                </div>
            </div>
        </header>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <footer>
            <div class="container">
                <strong><nav>
                    <ul class="bmenu">
                        <li><a href="{{ url_for('public.about') }}">About</a></li>
                        <li><a href="{{ url_for('public.contact') }}">Contact</a></li>
                    </ul>
                </nav></strong>
            </div>
        </footer>

    </body>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block content %}
    <h1>Hello, {{ user.nickname }}!</h1>
    {% for post in posts %}
    <div><p>{{ post.author.nickname }} says: <b> {{ post.body }}</b></p></div>
    {% endfor %}
{% endblock %}

app/templates/user.html
<!--extends base layout-->
{% extends "base.html" %}

{% block content %}
    <table>
        <tr valign="top">
            <td><img src="{{ user.avatar(128) }}"></td>
            <td>
                <h1>User: {{ user.nickname }}</h1>
                {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
                {% if user.last_seen %}<p><i>Last visited: {{ user.last_seen }}</i></p>{% endif %}
                {% if user.id == g.user.id %}<p><a href="{{ url_for('edit') }}">Edit</a></p>{% endif %}
            </td>
        </tr>
    </table>
    <hr>
    {% for post in posts %}
        {% include 'post.html' %}
    {% endfor %}
{% endblock %}